In [1]:
import pandas as pd
import numpy as np

In [2]:
shampoo = pd.read_excel('./data/shampoo_naver_10page.xlsx')
# 구글드라이브 경로
# 경로 설정 전 마운트 및 cd 로 경로 설정 우선 해주세요
# shampoo = pd.read_excel('./Crawling/shampoo_naver_10page.xlsx')
shampoo.head()

title  \
0   로더베르 시그니처 퍼퓸 샴푸 베이비파우더 1000ml   
1    제이숲 딥그린제이 아로마 샴푸 일랑일랑 1000ml   
2            모다모다 프로체인지 블랙샴푸 300g   
3             에스큐제약 모나다 샴푸 1000ml   
4  아모스 녹차실감 산뜻한 타입 지성 모발용 샴푸 500g   

                                           spec_list    price  rate opinion  
0  ['일반샴푸', '세정력', '풍부한 거품', '향', '저자극', '약산성', '...   9,900원   4.8   7,980  
1  ['지성', '건성', '민감성', '모든 모발용', '일반샴푸', '패스트샴푸',...  14,900원   4.7   3,307  
2  ['모든 모발용', '탈모샴푸', '저자극', '계면활성제 프리', '파라벤 프리'...  25,650원   4.6  15,302  
3                  ['모든 모발용', '일반샴푸', '세정력', '모발영양']  52,300원   4.8   1,234  
4  ['두피샴푸', '세정력', '상쾌함', '저자극', '촉촉함(수분공급)', '실리...  13,830원   4.8  12,955

In [3]:
shampoo['spec_list'] = shampoo['spec_list'].apply(lambda x: x.replace('[',''))

In [4]:
shampoo['spec_list'] = shampoo['spec_list'].apply(lambda x: x.replace(']',''))

In [5]:
shampoo['spec_list']

0      '일반샴푸', '세정력', '풍부한 거품', '향', '저자극', '약산성', '모...
1      '지성', '건성', '민감성', '모든 모발용', '일반샴푸', '패스트샴푸', ...
2      '모든 모발용', '탈모샴푸', '저자극', '계면활성제 프리', '파라벤 프리',...
3                        '모든 모발용', '일반샴푸', '세정력', '모발영양'
4      '두피샴푸', '세정력', '상쾌함', '저자극', '촉촉함(수분공급)', '실리콘...
                             ...                        
361    '일반샴푸', '세정력', '향', '상쾌함', '촉촉함(수분공급)', '각질케어'...
362                       '모든 모발용', '일반샴푸'', '촉촉함(수분공급)'
363    '모든 모발용', '일반샴푸', '세정력', '저자극', '촉촉함(수분공급)', '...
364                                 '염색 모발용', '향', '저자극'
365                        '두피샴푸', '모든 모발용', '촉촉함(수분공급)'
Name: spec_list, Length: 366, dtype: object

In [6]:
shampoo['spec_list'].apply(lambda x: x.split(','))

0      ['일반샴푸',  '세정력',  '풍부한 거품',  '향',  '저자극',  '약산...
1      ['지성',  '건성',  '민감성',  '모든 모발용',  '일반샴푸',  '패스...
2      ['모든 모발용',  '탈모샴푸',  '저자극',  '계면활성제 프리',  '파라벤...
3                   ['모든 모발용',  '일반샴푸',  '세정력',  '모발영양']
4      ['두피샴푸',  '세정력',  '상쾌함',  '저자극',  '촉촉함(수분공급)',...
                             ...                        
361    ['일반샴푸',  '세정력',  '향',  '상쾌함',  '촉촉함(수분공급)',  ...
362                   ['모든 모발용',  '일반샴푸'',  '촉촉함(수분공급)']
363    ['모든 모발용',  '일반샴푸',  '세정력',  '저자극',  '촉촉함(수분공급...
364                             ['염색 모발용',  '향',  '저자극']
365                    ['두피샴푸',  '모든 모발용',  '촉촉함(수분공급)']
Name: spec_list, Length: 366, dtype: object

In [7]:
# shampoo['specs'] = shampoo['spec_list'].apply(lambda x: x.split('/'))
# shampoo.head()

In [8]:
# shampoo['spec_list'].apply(lambda x: (' ').join(x))

In [9]:
shampoo.head()

title  \
0   로더베르 시그니처 퍼퓸 샴푸 베이비파우더 1000ml   
1    제이숲 딥그린제이 아로마 샴푸 일랑일랑 1000ml   
2            모다모다 프로체인지 블랙샴푸 300g   
3             에스큐제약 모나다 샴푸 1000ml   
4  아모스 녹차실감 산뜻한 타입 지성 모발용 샴푸 500g   

                                           spec_list    price  rate opinion  
0  '일반샴푸', '세정력', '풍부한 거품', '향', '저자극', '약산성', '모...   9,900원   4.8   7,980  
1  '지성', '건성', '민감성', '모든 모발용', '일반샴푸', '패스트샴푸', ...  14,900원   4.7   3,307  
2  '모든 모발용', '탈모샴푸', '저자극', '계면활성제 프리', '파라벤 프리',...  25,650원   4.6  15,302  
3                    '모든 모발용', '일반샴푸', '세정력', '모발영양'  52,300원   4.8   1,234  
4  '두피샴푸', '세정력', '상쾌함', '저자극', '촉촉함(수분공급)', '실리콘...  13,830원   4.8  12,955

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
# CountVectorizer로 학습시켰더니 2654개 샴푸에 대한 1983개 스펙의 '스펙 매트릭스'가 생성되었다.
count_vect = CountVectorizer(min_df=0, ngram_range=(1, 1)) 
#min_df: 단어장에 들어갈 최소빈도, ngram_range: 1 <= n <= 2
specs_mat = count_vect.fit_transform(shampoo['spec_list'])
print(specs_mat.shape)

(366, 44)


In [12]:
print(specs_mat)

  (0, 29)	1
  (0, 20)	1
  (0, 40)	1
  (0, 2)	1
  (0, 30)	1
  (0, 25)	1
  (0, 11)	1
  (1, 29)	1
  (1, 20)	1
  (1, 40)	1
  (1, 2)	1
  (1, 30)	1
  (1, 11)	1
  (1, 31)	1
  (1, 4)	1
  (1, 13)	1
  (1, 9)	1
  (1, 12)	1
  (1, 38)	1
  (1, 32)	1
  (1, 15)	1
  (1, 17)	1
  (1, 6)	1
  (1, 39)	1
  (1, 8)	1
  :	:
  (361, 24)	1
  (362, 29)	1
  (362, 9)	1
  (362, 12)	1
  (362, 34)	1
  (362, 23)	1
  (363, 29)	1
  (363, 20)	1
  (363, 30)	1
  (363, 11)	1
  (363, 9)	1
  (363, 12)	1
  (363, 34)	1
  (363, 23)	1
  (363, 1)	1
  (363, 16)	1
  (363, 14)	1
  (364, 30)	1
  (364, 12)	1
  (364, 26)	1
  (365, 9)	1
  (365, 12)	1
  (365, 6)	1
  (365, 34)	1
  (365, 23)	1


In [24]:
specs_mat.toarray()

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 3, 0, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [13]:
count_vect.vocabulary_

{'일반샴푸': 29,
 '세정력': 20,
 '풍부한': 40,
 '거품': 2,
 '저자극': 30,
 '약산성': 25,
 '모발영양': 11,
 '지성': 31,
 '건성': 4,
 '민감성': 13,
 '모든': 9,
 '모발용': 12,
 '패스트샴푸': 38,
 '천연샴푸': 32,
 '비듬샴푸': 15,
 '산성샴푸': 17,
 '두피샴푸': 6,
 '퍼퓸샴푸': 39,
 '머릿결개선': 8,
 '상쾌함': 18,
 '촉촉함': 34,
 '수분공급': 23,
 '트러블케어': 36,
 '각질케어': 1,
 '유분제거': 28,
 '청량감': 33,
 '비듬케어': 16,
 '손상케어': 22,
 '탈모샴푸': 35,
 '계면활성제': 5,
 '프리': 41,
 '파라벤': 37,
 '실리콘': 24,
 '가는': 0,
 '손상': 21,
 '건선': 3,
 '피부염성': 42,
 '한방샴푸': 43,
 '볼륨효과': 14,
 '염색': 26,
 '웨이브': 27,
 '샴푸바': 19,
 '드라이샴푸': 7,
 '모발보호': 10}

In [27]:
# CountVectorizer로 학습시켰더니 366개 샴푸에 대한 338개 스펙의 '스펙 매트릭스'가 생성되었다.
count_vect = CountVectorizer(min_df=0, ngram_range=(1, 2)) 
#min_df: 단어장에 들어갈 최소빈도, ngram_range: 1 <= n <= 2
specs_mat = count_vect.fit_transform(shampoo['spec_list'])
print(specs_mat.shape)

(366, 338)


In [28]:
count_vect.vocabulary_

{'일반샴푸': 221,
 '세정력': 159,
 '풍부한': 315,
 '거품': 12,
 '저자극': 242,
 '약산성': 200,
 '모발영양': 73,
 '일반샴푸 세정력': 230,
 '세정력 풍부한': 173,
 '풍부한 거품': 316,
 '거품 저자극': 20,
 '저자극 약산성': 247,
 '약산성 모발영양': 201,
 '지성': 254,
 '건성': 25,
 '민감성': 103,
 '모든': 69,
 '모발용': 75,
 '패스트샴푸': 308,
 '천연샴푸': 267,
 '비듬샴푸': 117,
 '산성샴푸': 136,
 '두피샴푸': 43,
 '퍼퓸샴푸': 311,
 '머릿결개선': 57,
 '상쾌함': 144,
 '촉촉함': 285,
 '수분공급': 181,
 '트러블케어': 297,
 '각질케어': 2,
 '유분제거': 211,
 '청량감': 274,
 '비듬케어': 127,
 '손상케어': 176,
 '지성 건성': 256,
 '건성 민감성': 30,
 '민감성 모든': 106,
 '모든 모발용': 70,
 '모발용 일반샴푸': 93,
 '일반샴푸 패스트샴푸': 239,
 '패스트샴푸 천연샴푸': 309,
 '천연샴푸 비듬샴푸': 270,
 '비듬샴푸 산성샴푸': 121,
 '산성샴푸 두피샴푸': 137,
 '두피샴푸 퍼퓸샴푸': 52,
 '퍼퓸샴푸 머릿결개선': 312,
 '머릿결개선 세정력': 62,
 '거품 상쾌함': 16,
 '상쾌함 저자극': 150,
 '저자극 촉촉함': 251,
 '촉촉함 수분공급': 286,
 '수분공급 트러블케어': 196,
 '트러블케어 각질케어': 298,
 '각질케어 유분제거': 9,
 '유분제거 청량감': 219,
 '청량감 비듬케어': 278,
 '비듬케어 손상케어': 133,
 '손상케어 모발영양': 178,
 '탈모샴푸': 287,
 '계면활성제': 41,
 '프리': 317,
 '파라벤': 306,
 '실리콘': 198,
 '모발용 탈모샴푸': 98,
 '탈모샴푸 저자극': 294,


In [29]:
# CountVectorizer로 학습시켰더니 2654개 샴푸에 대한 1983개 스펙의 '스펙 매트릭스'가 생성되었다.
count_vect = CountVectorizer(min_df=0, ngram_range=(1, 3)) 
#min_df: 단어장에 들어갈 최소빈도, ngram_range: 1 <= n <= 2
specs_mat = count_vect.fit_transform(shampoo['spec_list'])
print(specs_mat.shape)

(366, 946)


In [30]:
count_vect.vocabulary_

{'일반샴푸': 625,
 '세정력': 460,
 '풍부한': 894,
 '거품': 38,
 '저자극': 696,
 '약산성': 576,
 '모발영양': 214,
 '일반샴푸 세정력': 655,
 '세정력 풍부한': 499,
 '풍부한 거품': 895,
 '거품 저자극': 59,
 '저자극 약산성': 708,
 '약산성 모발영양': 577,
 '일반샴푸 세정력 풍부한': 666,
 '세정력 풍부한 거품': 500,
 '풍부한 거품 저자극': 903,
 '거품 저자극 약산성': 62,
 '저자극 약산성 모발영양': 709,
 '지성': 731,
 '건성': 80,
 '민감성': 330,
 '모든': 187,
 '모발용': 216,
 '패스트샴푸': 881,
 '천연샴푸': 766,
 '비듬샴푸': 356,
 '산성샴푸': 402,
 '두피샴푸': 125,
 '퍼퓸샴푸': 886,
 '머릿결개선': 161,
 '상쾌함': 419,
 '촉촉함': 812,
 '수분공급': 515,
 '트러블케어': 852,
 '각질케어': 9,
 '유분제거': 601,
 '청량감': 788,
 '비듬케어': 386,
 '손상케어': 509,
 '지성 건성': 734,
 '건성 민감성': 89,
 '민감성 모든': 335,
 '모든 모발용': 188,
 '모발용 일반샴푸': 279,
 '일반샴푸 패스트샴푸': 689,
 '패스트샴푸 천연샴푸': 882,
 '천연샴푸 비듬샴푸': 775,
 '비듬샴푸 산성샴푸': 370,
 '산성샴푸 두피샴푸': 403,
 '두피샴푸 퍼퓸샴푸': 150,
 '퍼퓸샴푸 머릿결개선': 887,
 '머릿결개선 세정력': 169,
 '거품 상쾌함': 45,
 '상쾌함 저자극': 434,
 '저자극 촉촉함': 722,
 '촉촉함 수분공급': 813,
 '수분공급 트러블케어': 558,
 '트러블케어 각질케어': 853,
 '각질케어 유분제거': 23,
 '유분제거 청량감': 617,
 '청량감 비듬케어': 795,
 '비듬케어 손상케어': 394,
 '손상케어 

In [31]:
# 두피 유형(Type) 입력시 : 리뷰수, 평점 4.7이상, 상위 10개 항목 출력
def recommend(Type) :
    result = shampoo[shampoo['spec_list'].str.contains(Type)]
    result = result[result['rate'] > 4.6]
    result.sort_values('opinion', ascending = False, inplace = True, ignore_index = True)
    return result[:10]

In [32]:
# 코사인 유사도에 의해 2653개 영화 각각 유사한 영화들이 계산됨
from sklearn.metrics.pairwise import cosine_similarity
specs_sim = cosine_similarity(specs_mat, specs_mat)

print(specs_sim.shape)
print(specs_sim[:6])

(366, 366)
[[1.         0.24019223 0.0410305  ... 0.21516574 0.09622504 0.        ]
 [0.24019223 1.         0.07884165 ... 0.33075929 0.09245003 0.22880216]
 [0.0410305  0.07884165 1.         ... 0.12712835 0.14213381 0.15075567]
 [0.27216553 0.26148818 0.15075567 ... 0.52704628 0.11785113 0.25      ]
 [0.14433757 0.2773501  0.21320072 ... 0.2981424  0.08333333 0.23570226]
 [0.27972712 0.430005   0.20659217 ... 0.13000542 0.14535047 0.10277831]]


In [33]:
# 자료를 정렬하는 것이 아니라 순서만 알고 싶다면 argsort
# 유사도가 높은 영화를 앞에서부터 순서대로 보여줌
# 0번째 영화의 경우 유사도 순서 : 0번, 3494번, 813번, ..., 2401 순서
specs_sim_sorted_ind = specs_sim.argsort()[:, ::-1] # 전체를 -1칸 간격으로
print(specs_sim_sorted_ind[:5])

[[  0  69 335 ... 184 187 365]
 [  1 143 129 ... 298 242 336]
 [  2 274  14 ... 294 232 170]
 [  3 215 178 ... 230 232 239]
 [  4 276  85 ...  64 238 262]]


In [34]:
recommend('지성')

title  \
0              RAUSCH 씨위드 디그리징 샴푸 200ml   
1  아베다 인바티 어드밴스드™ 엑스폴리에이팅 샴푸 라이트 1000ml   
2                케라시스 두피 프레쉬 쿨 샴푸 750ml   
3          케라시스 프로폴리스 에너지 플러스 샴푸 1000ml   
4                 폴미첼 티트리 스페셜 샴푸 1000ml   
5             케라시스 샤이닝 데미지 케어 샴푸 4000ml   
6                노비드 아유르베다 쿨멘솔 샴푸 700ml   
7       아로마티카 티트리 퓨리파잉 지성 두피용 샴푸 1000ml   
8                 아모스 퓨어스마트 샴푸 프레시 500g   
9              앙방 약산성 퍼퓸 샴푸 체리블라썸 550ml   

                                           spec_list     price  rate opinion  
0                                '지성', '일반샴푸', '세정력'   18,500원   4.8     957  
1  '지성', '가는 모발용', '일반샴푸', '두피샴푸', '세정력', '풍부한 거품...  110,810원   4.8     921  
2  '지성', '건성', '민감성', '가는 모발용', '염색 모발용', '웨이브 모발...    2,880원   4.7     861  
3  '지성', '건성', '민감성', '가는 모발용', '염색 모발용', '웨이브 모발...    4,890원   4.7     842  
4        '지성', '모든 모발용', '일반샴푸', '촉촉함(수분공급)', '비듬케어'   29,870원   4.8     813  
5  '지성', '건성', '민감성', '가는 모발용', '염색 모발용', '웨이브 모발...    9,960원   4.7   8,003  
6  '지성', '모든 모발용', '일반샴푸', '비듬샴푸', '두피샴푸', '세정력',...    2,670원   4.7     780  
7  '지성', '일반샴푸', '풍부한 거품', '상쾌함', '유분제거', '계면활성제 ...   22,550원   4.8      70  
8  '지성', '두피샴푸', '세정력', '풍부한 거품', '촉촉함(수분공급)', '비...    9,280원   4.7   7,159  
9  '지성', '건성', '민감성', '모든 모발용', '일반샴푸', '탈모샴푸', '...   19,900원   4.7     609

In [35]:
# 인자로 입력된 movies_df DataFrame에서 'title' 컬럼이 입력된 title_name 값인 DataFrame추출
title_shampoo = shampoo[shampoo['title'] == 'RAUSCH 씨위드 디그리징 샴푸 200ml']
title_shampoo

title            spec_list    price  rate opinion
294  RAUSCH 씨위드 디그리징 샴푸 200ml  '지성', '일반샴푸', '세정력'  18,500원   4.8     957

In [36]:
title_index = title_shampoo.index.values
title_index

array([294], dtype=int64)

In [37]:
similar_indexes = specs_sim_sorted_ind[title_index, :10]
similar_indexes

array([[294, 123,  84, 212,  19, 208, 178, 215, 297, 229]], dtype=int64)

In [38]:
# 추출된 top_n index들 출력. top_n index는 2차원 데이터 임.
# dataframe에서 index로 사용하기 위해서 2차원 array를 1차원 array로 변경
similar_indexes = similar_indexes.reshape(-1)
print(similar_indexes)

[294 123  84 212  19 208 178 215 297 229]


In [39]:
shampoo.iloc[similar_indexes]

title  \
294           RAUSCH 씨위드 디그리징 샴푸 200ml   
123  록시땅 퓨리파잉 프레쉬니스 샴푸 에코 지성 500ml(리필)   
84                  클리어 맨 딥클린 샴푸 650ml   
212           미쟝센 퍼펙트 세럼 스타일링 샴푸 680ml   
19                 알페신 카페인 샴푸 C1 250ml   
208                    애터미 한방 샴푸 500ml   
178              미엘 프로페셔널 스캘프 샴푸 800ml   
215               키라니아 단백질 볼륨 샴푸 500ml   
297                  리즈케이 알블랙 샴푸 450ml   
229       더마힐 헤어 컨디셔닝 샴푸 릴렉스 플러스 500ml   

                                      spec_list    price  rate opinion  
294                         '지성', '일반샴푸', '세정력'  18,500원   4.8     957  
123                  '지성', '일반샴푸', '세정력', '상쾌함'  27,220원   4.9   1,050  
84   '지성', '일반샴푸', '세정력', '유분제거', '청량감', '비듬케어'   4,500원   4.7   1,318  
212                      '일반샴푸', '세정력', '머릿결개선'   3,100원   4.8   1,103  
19                       '지성', '일반샴푸', '실리콘 프리'   6,460원   4.7  10,368  
208                  '일반샴푸', '세정력', '모발영양',약산성'   8,990원   4.7     703  
178                     '모든 모발용', '일반샴푸', '세정력'  33,000원   4.8     176  
215                     '모든 모발용', '일반샴푸', '세정력'   5,770원   4.7   2,128  
297              '모든 모발용', '일반샴푸', '세정력', '저자극'  19,010원   4.5     466  
229        '일반샴푸', '세정력', '각질케어', '약산성', '모발영양'  55,000원   4.8     344